import { parseCookies } from "../helpers/";
import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Menu from "../components/Menu/menu";
import TopDashboard from "@/components/TopDashboard/topDashboard";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ data }) {
	return (
		<>
			<Head>
				<title>Code Book</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/CodeBook.ico" />
			</Head>
			<main className={styles.container}>
				<Menu />
				<div>
				<TopDashboard  name={data}/>
				</div>
				
			</main>
		</>
	);
}
Home.getInitialProps = async ({ req, res }) => {
	const data = parseCookies(req);

	if (res) {
		if (Object.keys(data).length === 0 && data.constructor === Object) {
			res.writeHead(301, { Location: "/connexion" });
			res.end();
		}
	}

	return {
		data: data
	};
};
